### ISSUE TITLE
Please rethink new class names

### ISSUE THREAD

**Issue by koppor** [cliftonlabs/json-simple#10]
`JSONObject` and  `JsonObject` just differ in their names. Thus, on winows, Only one of these classes appears:

![grabbed_20161018-225242](https://cloud.githubusercontent.com/assets/1366654/19495932/a68efcc0-9585-11e6-8167-8184c19a59dc.png)

Could you maybe create a new package for the non-deprecated classes? Maybe `org.json.simpler`?

**Comment by loegering** [comment]
Thanks for reporting this issue, Oliver. I completely forgot about case insensitive file browsers while designing this. I want to make clear that json-simple will work if it is imported in your project. I use this library in production windows environments everyday. This can also be confirmed in the first answer (assuming you're using the JAR and not adding the classes to your class path individually): http://stackoverflow.com/questions/10890805/case-sensitivity-of-java-class-names

Now to solving the issue. I want the non-deprecated class names to be as descriptive and usable as possible. I think the names `JsonObject` and `JsonArray` are very reasonable in that regard. Unfortunately, the old version uses `JSONObject` and `JSONArray` they are deprecated so your IDE should notify you that you've mixed them up, it also indicates that they need replacement if you're upgrading to the 2.\* version. Since they are deprecated, they will be removed in the next major release of the library. So, I think the non-deprecated class names are not an issue going forward.

Since the names are probably going to stay the same, there's a problem with moving the non-deprecated classes to a new package. Moving/renaming them would be a backwards incompatible change. Meaning a major release, that the deprecated classes would have been dropped in anyway. Before I do that, I want to finish the feature set in the 2.\* version first. That way those interested can incrementally upgrade their project instead of being forced to do it all at once.

I can't speak for other case insensitive environments, but for windows it's very odd as this excerpt from https://en.wikipedia.org/wiki/Case_sensitivity explains:
Old Windows filesystems (VFAT, FAT32) are not case-sensitive but are case-preserving. The original FAT12 filesystem was case-insensitive and not case-preserving (so that a file saved as readme.txt or as Readme.txt is shown as README.TXT).[7] Current Windows file systems, like NTFS, are case-sensitive; that is a readme.txt and a Readme.txt can exist in the same directory. However, the API for file access in Windows applications is case-insensitive, which makes filenames case-insensitive from the application's point of view. Therefore, applications only have access to one of the files whose filenames only differ in case, and some commands may fail if the filename provided is ambiguous.[8]

I'm very sorry for any inconvenience this may have caused any contributors or those curious about the library's inner workings, I would love to have your help. It looks like the non-deprecated classes are displayed in your screenshot though. Those would be the classes necessary to do further development for the library since the deprecated ones shouldn't typically be changed. However, as you're aware that's not the full source code.

To see the full source in a case insensitive environment, I suggest these workarounds until 3.\* is released:
1) Checkout https://cliftonlabs.github.io/json-simple/ to download and import the json-simple project, javadocs, and source JARs into a new project in an IDE of your choosing. This way you can use it and see its javadocs and source in the IDE. However, this won't allow you to contribute to json-simple. This would be the recommended course of action for those that just want to see the source and maybe use it a bit.

2) Do the above with a tool like maven or gradle. Again this won't allow you to contribute to json-simple. This would be the recommended course of action if you're using the library in a project and want to be able to see the javadocs and source while you're developing.

3) I don't recommend it, but it's interesting... windows 10 can differentiate between files with different case with a bash shell environment. You might be able to figure something out from there? You can find more information about it here: https://msdn.microsoft.com/en-us/commandline/wsl/about

4) A dedicated VM (like from Oracle's VirtualBox) for development on json-simple in an OS that does have a case sensitive file API and browser. This would be the recommended course of action for those that want to contribute to json-simple.

I hope this helps. Please share any solutions you've come up with or found so that others may benefit from it too.

**Comment by loegering** [comment]
All of that said, thinking about the fact that `JsonArray` and `JsonObject` are based on List and Map and won't validate data inside themselves until it is serialized to JSON, I think there could be an argument for changing the names to `JsonableList` and `JsonableMap` respectively. Just me thinking out loud, this fact is something that should be mentioned in the javadocs regardless though.

**Comment by koppor** [comment]
Thank you for the long answer! My main reason was to replace org.json (https://github.com/Mashape/unirest-java/issues/176) and I searched for a quick solution (drop-in-replacement) and to enable other developers to easily work with. I have to confess that I found it by using Android SDK's org.json implementation, even though it is not directly available in maven central and thus is an issue to reference to (https://github.com/Mashape/unirest-java/pull/179).

Since it seems that I am the only one wondering, I will close this issue.
