### ISSUE TITLE
Colons?

### ISSUE THREAD

**Issue by ericleb010** [cliftonlabs/json-simple#11]
Shouldn't the absence of a colon between a key and a value throw a DeserializationException? Seems that the parser recognizes its presence but doesn't actually enforce it.

**Comment by loegering** [comment]
Good eye, thanks, Eric. I'll make sure this is covered in test cases. I **think** the lexer handles this issue implicitly, but I'll make sure. I'll keep you updated.

**Comment by loegering** [comment]
As it turns out the lexer doesn't handle it, I've added it to the test cases. After careful consideration I think I will make this bug a feature. The library will never serialize a key value pair without a colon but it might save some people time in complicated configuration files by allowing it during deserialization. This is consistent with the precedence that the library allows trailing commas for deserialization, but will never output trailing commas upon serialization. A basic test demonstrating the feature is below. 

```
/** @param args the command line arguments to be ignored. */
public static void main(String[] args){
    JSONObject oldInvalidJson = (JSONObject)JSONValue.parse("{\"key\"\"value\"}");
    JsonObject newInvalidJson = Jsoner.deserialize("{\"key\"\"value\"}", new JsonObject());
    JSONObject oldValidJson = (JSONObject)JSONValue.parse("{\"key\":\"value\"}");
    JsonObject newValidJson = Jsoner.deserialize("{\"key\":\"value\"}", new JsonObject());
    /* Test output: */
    System.out.println("1.* invalid: " + oldInvalidJson.toString());
    System.out.println("2.* invalid: " + newInvalidJson.toJson());
    System.out.println();
    System.out.println("1.* valid:" + oldValidJson.toString());
    System.out.println("2.* valid:" + newValidJson.toJson());
}
```

Will output:

```
1.* invalid: {"key":"value"}
2.* invalid: {"key":"value"}

1.* valid:{"key":"value"}
2.* valid:{"key":"value"}
```
