### ISSUE TITLE
Null Pointer Exceptions

### ISSUE THREAD

**Issue by robweber** [cliftonlabs/json-simple#15]
Just wondering if there was any particular design reason why the convience methods like ```getLong()``` fail if the key in question is null rather than just returning the null value? 

My interest is that it's been kind of a pain recently that it does this. A REST API I've been using returns several keys that in json look like: 

```json
{
  key1: 2,
  key2: null,
  key3: 5
}
```

When attempting to call something like ```getLong("key2")``` I end up with a null pointer exception being thrown as the simple-json library does a cast ```return (Long) returnable``` at the end of the method. This means that in my own code I end up wrapping a lot of "check if null, if not get value, if so return null" into my methods. It would be nice if the simple-json lib simply returned null directly and then I could deal with the result value on my own. Things are further complicated when trying to build POJO type objects that load the values via the JsonObject in a constructor. I can deal with null values at runtime, but as soon as the error is thrown it halts everything. 

If I did the work and submitted a pull request to correct this would it be considered to merge in?

**Comment by loegering** [comment]
Sorry for the delayed response! The reason this is the case is because when you call, say, `apiObject.getLong("key2")` it's likely you expect a Long to be there or at least a Number to be there or at the very least a String that represents a Number to be there. Since that value isn't there as expected it's treated as an exceptional case. Which is there as a warning that says: "Woah! Just so you know there wasn't the kind of value you were expecting." so that you can be like: "eh, I know" (with a try-catch block) or "Oh, ****, abort! ABORT!" (hopefully still with a try-catch block to abort gracefully). I have a few recommendations you can try out:

1) If you have access to the API code you could try using error values instead of null or not putting in the key when it doesn't have a value.
2) If the key isn't there and you have a reasonable default (like an error value) you can simply do a `apiObject.getLongOrDefault("key2", -1)` call so that you get the value or the default value if it isn't there.
3) I'd consider reporting a bug if the API says a number should be there since a null isn't a valid number. On the other hand you can expect that the value might not be there and use a try-catch block for the exceptions you want to deal with (in this case a NPE) like in this example:
```
public static void main(String[] args) throws DeserializationException {
	String myJsonString = "{\"key1\": 2,\"key2\": null,\"key3\": \"5\"}";
	JsonObject apiObject = (JsonObject)Jsoner.deserialize(myJsonString);
	long number;
	try {
		number = apiObject.getLong("key2");
	}catch(NullPointerException caught) {
		/*Woah, the API docs said there should be a Number here, but there wasn't. Use a default value for now, and maybe submit a bug report on the API. */
		number = -1;
	}
	System.out.println("API 'key2' results:");
	System.out.println(number);
}
```
4) If you don't know what kind of value should be there, I'd recommend using the `apiObject.get("key2")` method since that will allow you raw access to the key's value without assumptions as an `Object` so you can deal with it manually.

Hope this helps!

**Comment by robweber** [comment]
Thanks for taking the time to answer this. My use case is such that I'm not the developer of the API, simply consuming it via REST calls. For better or worse what ends up happening is that a REST call could return any number of states on an object. State A may include values for keys, State B may include nulls for some values as the state of the object means those values aren't initialized. Granted the API should handle these cases but I'm just the consumer dealing with this; I'm sure the API developer has their reasons for doing this as well. 

Because of this items 1 and 2 don't make sense for me. The default value is null, it's not initialized. As such I end up with a lot of code that looks like the following: 

```java
/**
	 * @return the estimated print time for the file, in seconds
	 */
	public Long getEstimatedPrintTime(){
		Long result = null;

		if(m_job.get("estimatedPrintTime") != null)
		{
			result =  m_job.getLong("estimatedPrintTime");
		}

		return result;
	}
```
Much like the try-catch solution this just leads to a lot of redundant code. In my design opinion returning the null and leaving it up to me to decide if this is the type of code that should produce an exception would have been better. Was there any thought to explicitly adding a "throws" declaration to these method calls on your end? That would at least let developers know this is what is going to happen should the value not exist. Coming from the v1 implementation of simple-json that is what I expected from a Map type object. 

Granted there are a lot of things I could do on my end as well (subclass based on state, check the state before doing the getLong() call, etc, etc) but that would involve me knowing under exactly what conditions the API is going to return these null values and just create a lot of headache. I appreciate the time taken to answer the question, it sounds like throwing the NullPointerException was a definite design choice in this case.

**Comment by loegering** [comment]
I agree it is rather strange there isn't a @throws clause for the NPE when the others are covered. I've added it to my todo list. Thanks, for the feedback!

**Comment by loegering** [comment]
Taking a second look at this... the API is a bit inconsistent. When null is there on a getBoolean() call it will allow null through, but getInteger() will throw NPE. I've updated the numerical convenience gets to allow a null return like the rest of the API (which is more consistent with Java's Map and version 1 of the library) and will be part of the 2.2.0 release. Thanks for finding this and reporting it.

**Comment by loegering** [comment]
Officially part of the 2.2.0 release.

**Comment by robweber** [comment]
Great - I'll test this out. Appreciate you going through and looking into it.
