### ISSUE TITLE
getArray() and getObject are needed!!!

### ISSUE THREAD

**Issue by MikePryadko** [cliftonlabs/json-simple#16]
I use that library for few days and now I don't understand why it has such methods like `getString()`/`getFloat()` but it does not have methods `JsonArray getArray()` and `JsonObject getObject()`
>:-|
example:
```javascript
[
    {
        "abc": "mock",
        "def": [4, 8, 15, 16, 23, 42]
    },
    {
        "abc": "duck",
        "def": [1, 2, 3, 4, 5, 6]
    }
]
```
In my opinion the only way to deal with it is that way:
```java
JsonArray myArray = (JsonArray)Jsoner.deserialize(myJsonString);
int myNumberSix = myArray.getObject(1).getArray("def").getInteger(5);
```
Am I crazy???

**Comment by loegering** [comment]
Sorry for the delayed response. You can use jsonObject.getCollection("") or jsonArray.getCollection(0) and jsonArray.getMap(0) or jsonObject.getMap("") to get a Collection and Map respectively. Since JsonArray and JsonObject is a Collection and a Map respectively you can tell the method what kind to expect there like in the following example (which is very similar to what you wanted in your issue):
```
String myJsonString = "[{\"abc\": \"mock\",\"def\": [4, 8, 15, 16, 23, 42]},{\"abc\": \"duck\",\"def\": [1, 2, 3, 4, 5, 6]}]";
JsonArray myArray = (JsonArray)Jsoner.deserialize(myJsonString);
int myNumberSix = myArray.<JsonObject>getMap(1).<JsonArray>getCollection("def").getInteger(5);
System.out.println(myNumberSix);
```

**Comment by MikePryadko** [comment]
Thank you, but I simply used another lib (JSONUtil) which allow using described functionality ;) 
Using your library was a legacy... and now I don't understand the reasons (for you and others) to develop a new library if the same one is existed :) it's illogical 


Best regards

**Comment by loegering** [comment]
I'm glad you found a library that works for your use case!
