### ISSUE TITLE
Possible optimization in memory use

### ISSUE THREAD

**Issue by DarkSideOfTheBit** [cliftonlabs/json-simple#25]
Maybe I'm missing something.

In JsonObject.java and JsonArray.java, when method "toJson(Writer _writable_) "is called, output is built by using _writable_.write(Jsoner.serialize(Object)), which results in Jsoner.serialize(Object) creating a StringWriter to call Jsoner.serialize(Object, Writer), and finally the String created in the StringWriter is returned and written into _writable_

¿Couldn't we call directly "Jsoner.serialize(Object, _writable_)" instead of "_writable_.write(Jsoner.serialize(Object))" to avoid the creation of a possibly unneccesary StringWriter? That would reduce memory footprint, mainly when outputting big objects.

You can do this in lines 329 of JsonArray.java, and in lines 647 and 649 of JsonObject.java.

In the same way, you could probably save another StringWriter by using Jsonable.toJson(_writableDestination_) instead of _writableDestination_.write(Jsonable.toJson()) in line 637 of Jsoner.java 

I came across this while handling very big JsonObjects and ending up in out of heap space problems.

**Comment by loegering** [comment]
I don't think you're missing anything - thanks for the write up. Made it really easy to investigate. I've made the changes you've suggested and the tests all pass. I don't have time to benchmark the performance differences. I expect these changes will perform slightly better as garbage collection won't run quite as much since all of the extra writers you've mentioned are scoped to live very briefly. Obviously your mileage will vary based on whether you're doing large data blobs or lots of small fields in your JSON, with the latter seeing more improvement. I just can't say how much improvement since I haven't done a performance comparison.

As to your heap space problems it really depends on your JSON having many small fields or not and how aggressive your garbage collection is. I don't expect this change to be game changing though since it is likely an available computing resources for the JVM versus the size of your JSON problem. Generally, when you get to large data sizes and you can't increase available computing resources, you need to adapt strategies in processing the data to avoid it all being in memory at once.
